version: '3.8'
services:

  database:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:6.4.1-alpine
    environment:
      - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://database:5432/postgres -schemas=flyway -user=user -password=password -connectRetries=10 migrate
    depends_on:
      - database