server:
  port: 8081
spring:
  application:
    name: voting_sessions
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    datasources:
      default:
        locations: classpath:db/migration